### ISSUE TITLE
Option to only see gutter

### ISSUE THREAD

**Issue by DinisCruz** [jacogr/atom-lcov-info#10]
In the main README.md you mention

> Highlights are configurable to either show as a line (default) or in the gutter (less obtrusive)

but i can't seem to find the option to set it

Sorry if it is in an obvious location

**Comment by DinisCruz** [comment]
I found a way to do it

I changed the default module.exports -> config -> default' value to 'gutter'

```
module.exports =
  config:
    highlightType:
      title: 'Highlight Type'
      description: 'Perform highlighting either on the line, or the gutter'
      type: 'string'
      default: 'gutter'
      enum: ['line', 'gutter']
    coveredType:
      title: 'Coverage Display'
      description: 'Display applies to everything or uncovered lines only'
      type: 'string'
      default: 'Covered & Uncovered Lines'
      enum: ['Covered & Uncovered Lines', 'Uncovered Lines Only']
```

And when I reloaded the window on the left and loaded the CC info (is that the only way to see the changes?) only the gutter was showing

![image](https://cloud.githubusercontent.com/assets/656739/5682308/d0c7a5f0-9816-11e4-87b6-5a765d93efe0.png)
